version: "3.9"

services:
    php:
        image: ferror/sylius-demo:sylius_php_prod
        deploy:
            endpoint_mode: vip
            mode: replicated
            replicas: 3
            placement:
                max_replicas_per_node: 6
            resources:
                reservations:
                    cpus: "1"
                    memory: 512M
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 90s
            rollback_config:
                parallelism: 2
                delay: 5s
                failure_action: pause
                monitor: 5s
                max_failure_ratio: 0
                order: stop-first
            update_config:
                parallelism: 2
                delay: 5s
                failure_action: pause
                monitor: 5s
                max_failure_ratio: 0
                order: stop-first
        depends_on:
            - mysql
        environment:
            DATABASE_URL: mysql://sylius:sylius_mysql_password@mysql/sylius_prod
            PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE:-UTC}
            APP_ENV: prod
            APP_DEBUG: 0
#        volumes:
#            - ./public/media:/srv/sylius/public/media:rw
        networks:
            - sylius
    
    nginx:
        image: ferror/sylius-demo:sylius_nginx
        deploy:
            endpoint_mode: vip
            mode: replicated
            replicas: 3
            placement:
                max_replicas_per_node: 6
            resources:
                reservations:
                    cpus: "1"
                    memory: 512M
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 90s
            rollback_config:
                parallelism: 2
                delay: 5s
                failure_action: pause
                monitor: 5s
                max_failure_ratio: 0
                order: stop-first
            update_config:
                parallelism: 2
                delay: 5s
                failure_action: pause
                monitor: 5s
                max_failure_ratio: 0
                order: stop-first
        depends_on:
            - php
#        volumes:
#            - ./public/media:/srv/sylius/public/media:ro
        networks:
            - sylius
        ports:
            - "80:80"

    mysql:
        image: mysql:5.7
        deploy:
            endpoint_mode: vip
            mode: replicated
            replicas: 1
            resources:
                reservations:
                    cpus: "2"
                    memory: 1024M
            placement:
                constraints: [ node.role == manager ]
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 0
            MYSQL_DATABASE: sylius_prod
            MYSQL_USER: sylius
            MYSQL_PASSWORD: sylius_mysql_password
# Let forget about volumes here             
#        volumes:
#            - ./docker/mysql/data:/var/lib/mysql:rw,delegated
        networks:
            - sylius

    visualizer:
        image: dockersamples/visualizer:stable
        ports:
            - "8080:8080"
        stop_grace_period: 1m30s
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        deploy:
            endpoint_mode: vip
            mode: replicated
            replicas: 1
            placement:
                constraints: [ node.role == manager ]
        networks:
            - sylius

networks:
    sylius:
        driver: overlay
