name: Docker Swarm

on:
    push:
        branches:
            - 'master'
        paths-ignore:
            - "*.md"
    pull_request:
        branches:
            - 'master'
        paths-ignore:
            - "*.md"

jobs:
    build-image:
        name: Build and Push Docker Image [${{ matrix.target }}]
        env:
            MYSQL_PASSWORD: sylius-mysql
            DOCKER_BUILDKIT: 1 # Requires Latest Buildx in docker CLI
            COMPOSE_DOCKER_CLI_BUILD: 1 # Requires Latest Buildx in docker compose CLI
        strategy:
            fail-fast: false
            matrix:
                target: [sylius_nginx,sylius_php_prod]
        
        runs-on: ubuntu-latest
        steps:
            -
                name: Set Up QEMU
                uses: docker/setup-qemu-action@v2
            -
                name: Set Up Docker Buildx
                uses: docker/setup-buildx-action@v2
                
            -
                name: Login to DockerHub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            -
                name: Build Image
                uses: docker/build-push-action@v3
                with:
                    push: true
                    platforms: linux/amd64,linux/arm64
                    context: "{{defaultContext}}"
                    tags: ferror/sylius-demo:${{ matrix.target }}
                    cache-from: type=gha
                    cache-to: type=gha
                    target: ${{ matrix.target }}
